const BASE_URL = process.env.NEXT_PUBLIC_BACKEND_URL;
// process.env.NODE_ENV === "development"
//   ? process.env.NEXT_PUBLIC_BACKEND_URL
//   : process.env.NEXT_PUBLIC_BACKEND_URL;

const products = [
  {
    category: 1,
    title: " Jasa Foto Produk Makanan dan Minuman 20 Foto",
    cover: "/assets/images/img-cover-product.png",
    price: "1.400.000",
    rate: 4.7,
    review: 223,
    city: "Yogyakarta",
  },
  {
    category: 1,
    title: " Jasa Foto Produk Makanan dan Minuman 20 Foto",
    cover: "/assets/images/img-cover-product.png",
    price: "1.400.000",
    rate: 4.7,
    review: 223,
    city: "Yogyakarta",
  },
  {
    category: 1,
    title: " Jasa Foto Produk Makanan dan Minuman 20 Foto",
    cover: "/assets/images/img-cover-product.png",
    price: "1.400.000",
    rate: 4.7,
    review: 223,
    city: "Yogyakarta",
  },
  {
    category: 1,
    title: " Jasa Foto Produk Makanan dan Minuman 20 Foto",
    cover: "/assets/images/img-cover-product.png",
    price: "1.400.000",
    rate: 4.7,
    review: 223,
    city: "Yogyakarta",
  },
  {
    category: 1,
    title: " Jasa Foto Produk Makanan dan Minuman 20 Foto",
    cover: "/assets/images/img-cover-product.png",
    price: "1.400.000",
    rate: 4.7,
    review: 223,
    city: "Yogyakarta",
  },
  {
    category: 1,
    title: " Jasa Foto Produk Makanan dan Minuman 20 Foto",
    cover: "/assets/images/img-cover-product.png",
    price: "1.400.000",
    rate: 4.7,
    review: 223,
    city: "Yogyakarta",
  },
  {
    category: 2,
    title: " Jasa Foto Produk Makanan dan Minuman 20 Foto",
    cover: "/assets/images/img-cover-product-2.png",
    price: "1.400.000",
    rate: 4.7,
    review: 223,
    city: "Malang",
  },
  {
    category: 2,
    title: " Jasa Foto Produk Makanan dan Minuman 20 Foto",
    cover: "/assets/images/img-cover-product-2.png",
    price: "1.400.000",
    rate: 4.7,
    review: 223,
    city: "Malang",
  },
  {
    category: 2,
    title: " Jasa Foto Produk Makanan dan Minuman 20 Foto",
    cover: "/assets/images/img-cover-product-2.png",
    price: "1.400.000",
    rate: 4.7,
    review: 223,
    city: "Malang",
  },
  {
    category: 2,
    title: " Jasa Foto Produk Makanan dan Minuman 20 Foto",
    cover: "/assets/images/img-cover-product-2.png",
    price: "1.400.000",
    rate: 4.7,
    review: 223,
    city: "Malang",
  },
  {
    category: 2,
    title: " Jasa Foto Produk Makanan dan Minuman 20 Foto",
    cover: "/assets/images/img-cover-product-2.png",
    price: "1.400.000",
    rate: 4.7,
    review: 223,
    city: "Malang",
  },
];

export { BASE_URL, products };
